use Mix.Config

# Configure your database
config :chatlag, Chatlag.Repo,
  username: "chatlag",
  # password: "ChatlagEfrat68",
  password: "chatlag",
  database: "chatlag",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :chatlag, ChatlagWeb.Endpoint,
  http: [port: 9040],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#

# https://chatlag.co.il/auth/facebook/callback&response_type=code&scope=email&state=edc95c6f906750c4675f6ba4c29ef8ba57d27aee6596af5
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# config :chatlag, ChatlagWeb.Endpoint,
#       http: [port: 4000],
#       https: [
#         port: 4001,
#         cipher_suite: :strong,
#         certfile: "priv/cert/selfsigned.pem",
#         keyfile: "priv/cert/selfsigned_key.pem"
#       ]

# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :chatlag, ChatlagWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/chatlag_web/{live,views}/.*(ex)$",
      ~r"lib/chatlag_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

config :chatlag, Chatlag.Mailer, adapter: Bamboo.LocalAdapter

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
